/* ============================================================
   export.js — PDF & PNG Export
   ============================================================ */

const HouseExport = (() => {

  function exportPNG(canvasEl, filename = "housemap-plan.png") {
    canvasEl.toBlob(blob => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 2000);
    }, "image/png", 1.0);
  }

  async function exportPDF(canvasEl, plan, filename = "housemap-plan.pdf") {
    if (typeof window.jspdf === "undefined") {
      alert("PDF library load nahi hui — internet connection check karein.");
      return;
    }
    const { jsPDF } = window.jspdf;

    const imgData = canvasEl.toDataURL("image/png", 1.0);

    // Choose orientation based on plot aspect ratio
    const landscape = plan.plot.w >= plan.plot.h;
    const doc = new jsPDF({
      orientation: landscape ? "landscape" : "portrait",
      unit: "pt",
      format: "a4"
    });

    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 24;

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("HouseMap AI Pro — Professional Floor Plan", margin, margin + 4);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(90);
    doc.text(
      `Plot Size: ${plan.plot.w}' x ${plan.plot.h}'  |  Total Area: ${plan.totalAreaSqFt} sq.ft (${plan.marlas} Marla)  |  Generated: ${new Date().toLocaleDateString()}`,
      margin, margin + 20
    );

    const imgTop = margin + 34;
    const availW = pageW - margin * 2;
    const availH = pageH - imgTop - margin - 60;

    const ratio = Math.min(availW / canvasEl.width, availH / canvasEl.height);
    const drawW = canvasEl.width * ratio;
    const drawH = canvasEl.height * ratio;
    const drawX = margin + (availW - drawW) / 2;

    doc.addImage(imgData, "PNG", drawX, imgTop, drawW, drawH);

    // Room schedule table below the drawing
    let ty = imgTop + drawH + 20;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(20);
    doc.text("Room Schedule", margin, ty);
    ty += 14;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60);
    const colW = [180, 100, 100, 100];
    doc.text("Room", margin, ty);
    doc.text("Size (ft)", margin + colW[0], ty);
    doc.text("Area (sq.ft)", margin + colW[0] + colW[1], ty);
    ty += 6;
    doc.setDrawColor(200);
    doc.line(margin, ty, pageW - margin, ty);
    ty += 12;

    plan.rooms.forEach(r => {
      if (ty > pageH - margin) {
        doc.addPage();
        ty = margin + 10;
      }
      doc.text(r.label || r.type, margin, ty);
      doc.text(`${r.w}' x ${r.h}'`, margin + colW[0], ty);
      doc.text(`${r.areaSqFt}`, margin + colW[0] + colW[1], ty);
      ty += 14;
    });

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by HouseMap AI Pro — M Ijaz", margin, pageH - 12);

    doc.save(filename);
  }

  return { exportPNG, exportPDF };
})();
